version: '3.8'

services:
  rideshare:
    build: ./rideshare
    ports:
      - "8081:81"
    container_name: rideshare

  food:
    build: ./food
    ports:
      - "8080:80"
    container_name: food

  music:
    build: ./music
    ports:
      - "8082:80"
    container_name: music

  realty:
    build: ./realty
    ports:
      - "8083:80"
    container_name: realty

  fitness:
    build: ./fitness
    ports:
      - "8084:80"
    container_name: fitness

  tours:
    build: ./tours
    ports:
      - "8085:80"
    container_name: tours
