version: '3.8'

services:
  rideshare:
    build: ./rideshare
    ports:
      - "8090:80"
    container_name: rideshare

  food:
    build: ./food
    ports:
      - "8091:80"
    container_name: food

  music:
    build: ./music
    ports:
      - "8092:80"
    container_name: music

  realty:
    build: ./realty
    ports:
      - "8093:80"
    container_name: realty

  fitness:
    build: ./fitness
    ports:
      - "8094:80"
    container_name: fitness

  tours:
    build: ./tours
    ports:
      - "8095:80"
    container_name: tours
